### ISSUE TITLE
Automate v24 isn't supported

### ISSUE THREAD

**Issue by pschoen2908** [automateps/AutomatePS.Health#8]
## Expected Behavior
Automate PS works in Automate v24.

## Actual Behavior
Automate PS works in Automate v24.

## Steps to Reproduce the Problem

  1. We run an Automate healthcheck every month and this fails after the upgrade to v24:.

Unsupported server major version: 24!
At C:\Program Files\WindowsPowerShell\Modules\AutomatePS\Functions\Public\Get-AMFolderRoot.ps1:66 char:37
+ ...   default           { throw "Unsupported server major version: $_!" }
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unsupported server major version: 24!:String) [], RuntimeException
    + FullyQualifiedErrorId : Unsupported server major version: 24!

## Specifications

  - AutomatePS Version:
                                                  automateps.5.1.1
  - AutomatePS.Health Version:
                                                  automateps.health.2.3.0
  - PowerShell Version:
                                                7
  - Automate Enterprise Version:
                                                   Automate v24.1.0.51

**Comment by KFFortra** [comment]
I got it working with Automate 24 by changing one file and then restarting PowerShell, let me know if you need help getting this to work.

Keith Fuller, Fortra Support

**Comment by sknijn** [comment]
Hi @KFFortra .

I am experiencing similar issues. What did you change exactly?

Regards,
Sander

**Comment by KFFortra** [comment]
Within the automatePS folder I changed the following file, added a reference to 23, 24 in there, saved that and then closed powershell before rerunning the process.

![image](https://github.com/user-attachments/assets/0edcefe8-3e7f-42fe-b85a-43508a7099b5)


This is in c:\users\youruser\appdata\autonateps\functions\public\get-amfolderroot.ps1

**Comment by davidseibel** [comment]
Support for a new version can either be simple, or complicated.

By that I mean if the underlying binaries for the Automate types (workflow, task, agent, etc.) haven't been upgraded to a new version, then adding support is "simple" in that the new version simply needs to be added to each function, similar to what KFFortra pointed out above.  However, more than just the Get-AMFolderRoot function needs to be changed.  Most functions need to be changed, see [here](https://github.com/automateps/AutomatePS/pull/34/commits/a0c1d39ab8632121f995d847aaa97dcfdd5640ab) for the changes that were required to add support for v23.

However, if Fortra releases new binaries for the new version, then that requires defining a whole new [classes file](https://github.com/automateps/AutomatePS/blob/master/Types/Automate.classes.v11.ps1).  This is somewhat labor intensive as I have to figure out what changed, type by type, and define all new classes in a new classes file.  In addition to that, I still have to go through each function and add support for the new version.

It might take me a few months to get around to adding v24 support.  If anyone else wants to attempt to do so, feel free, and then submit a PR.

**Comment by davidseibel** [comment]
This is not an issue with AutomatePS.Health.  This is an issue with AutomatePS.  I will log an issue in AutomatePS for you.
